"""baseline: adopt alembic (schema already up to date)

The `tournaments` table was hand-migrated up to this point via the raw SQL
files in backend/migrations/ (see 0001, 0002). This revision has no-op
upgrade/downgrade because the live schema already matches app.models —
it exists purely so `alembic upgrade head` creates the alembic_version
tracking table and marks it at this point. Future schema changes go
through `alembic revision --autogenerate` from here on.

Revision ID: d9613afa2379
Revises:
Create Date: 2026-07-02 03:06:40.465143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9613afa2379'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
